name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Trigger Render deployment
        run: |
          curl -X POST https://api.render.com/deploy/some-deploy-hook-url
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
